### ISSUE TITLE
Any way to access meta of tickets response?

### ISSUE THREAD

**Issue by stijnjanmaat** [HegartyMaths/php-groove-api#8]
Hi, 

The Groove API returns in its response a property 'meta', as it shows here in the docs: https://www.groovehq.com/docs/tickets#listing-tickets 
I don't believe this part is accessible trough your api, is it? Would be great i could do

`$client->tickets()->meta()`

or something.

Thanks

**Comment by DanKeeble** [comment]
Hi @stijnjanmaat,

I can try and get something out this week, otherwise feel free to open a PR!

Cheers

**Comment by stijnjanmaat** [comment]
Hi Daniel,

Thanks, I've been sick all week, will look at a PR next week!

**Comment by stijnjanmaat** [comment]
Hi Daniel, did you get a change to look at my PR? Thanks!

**Comment by DanKeeble** [comment]
Hi @stijnjanmaat, sorry for the delay. Tagging the release now.
